/*
===============================================================================
Magnitude Analysis
===============================================================================
Purpose:
    - To quantify data and group results by specific dimensions.
    - For understanding data distribution across categories.

SQL Functions Used:
    - Aggregate Functions: SUM(), COUNT(), AVG()
    - GROUP BY, ORDER BY
===============================================================================
*/

-- Find total customers by countries
SELECT
	country,
	COUNT(customer_key) AS number_of_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY number_of_customers DESC;

-- Find total customers by gender
SELECT
	gender,
	COUNT(customer_key) AS number_of_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY number_of_customers DESC;

-- Find total products by cateogry
SELECT
	category,
	COUNT(product_key) AS number_of_products
FROM gold.dim_products
GROUP BY category
ORDER BY number_of_products DESC;

-- What is the average cost in each category
SELECT
	category,
	ROUND(AVG(product_cost), 2) AS average_cost
FROM gold.dim_products
GROUP BY category
ORDER BY average_cost DESC;

-- What is the total revenue generated for each category
SELECT
	p.category,
	SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_products AS p 
ON p.product_key = f.product_key
GROUP BY p.category
ORDER BY total_revenue DESC;

-- Find total revenue generated by each customer
SELECT
	c.customer_key,
	c.first_name,
	c.last_name,
	SUM(f.sales_amount) AS totalrevenue
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_customers AS c
ON c.customer_key = f.customer_key
GROUP BY c.customer_key, 
		 c.first_name, 
		 c.last_name
ORDER BY totalrevenue DESC;

-- What is the distribution of sold items across countries
SELECT
	c.country,
	SUM(f.quantity) AS items_sold
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_customers AS c
ON c.customer_key = f.customer_key
GROUP BY c.country
ORDER BY items_sold DESC;
